scan_filter_chain:
- name: angle
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    # lower_angle: -0.7853981634
    # upper_angle: 0.7853981634
    #lower_angle: -0.8       # -45 DEG
    #upper_angle: 0.8        # 45 DEG
    lower_angle: -1.57       # -45 DEG
    upper_angle: 1.57        # 45 DEG